[package]
name = "day4"
version = "0.1.0"
authors = ["Adrian Goławski <adrian.golawski@yougov.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
md5 = "0.7.0"
